
package com.crossborder.entity;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import com.crossborder.service.ShipRate;

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-06-08T18:02:43.125+08:00
 * Generated source version: 2.7.14
 * 
 */
public final class ShipRate_ShipRateSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/ShipRate/", "ShipRate");

    private ShipRate_ShipRateSOAP_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ShipRate_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ShipRate_Service ss = new ShipRate_Service(wsdlURL, SERVICE_NAME);
        ShipRate port = ss.getShipRateSOAP();
        
        {
        System.out.println("Invoking getCountries...");
        GetCountriesRequest _getCountries_parameters = null;
        Countries _getCountries__return = port.getCountries(_getCountries_parameters);
        System.out.println("getCountries.result=" + _getCountries__return);


        }
        {
        System.out.println("Invoking getFeeByOrderCode...");
        HeaderRequest _getFeeByOrderCode_headerRequest = null;
        String _getFeeByOrderCode_orderCodeVal = "";
        javax.xml.ws.Holder<String> _getFeeByOrderCode_orderCode = new javax.xml.ws.Holder<String>(_getFeeByOrderCode_orderCodeVal);
        javax.xml.ws.Holder<String> _getFeeByOrderCode_ask = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _getFeeByOrderCode_sysTime = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _getFeeByOrderCode_msg = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _getFeeByOrderCode_baseFee = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _getFeeByOrderCode_regFee = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _getFeeByOrderCode_dealFee = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _getFeeByOrderCode_insurance = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _getFeeByOrderCode_totalFee = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _getFeeByOrderCode_currencyCode = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _getFeeByOrderCode_chargebackTime = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _getFeeByOrderCode_chargebackWorkDay = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _getFeeByOrderCode_shipTypeCode = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _getFeeByOrderCode_subShipType = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _getFeeByOrderCode_waybillCode = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _getFeeByOrderCode_discount = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<java.util.List<OtherFee>> _getFeeByOrderCode_otherFee = new javax.xml.ws.Holder<java.util.List<OtherFee>>();
        javax.xml.ws.Holder<String> _getFeeByOrderCode_originBaseFee = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _getFeeByOrderCode_originAddons = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _getFeeByOrderCode_stDealFee = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _getFeeByOrderCode_stRegFee = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _getFeeByOrderCode_feeWeight = new javax.xml.ws.Holder<String>();
        port.getFeeByOrderCode(_getFeeByOrderCode_headerRequest, _getFeeByOrderCode_orderCode, _getFeeByOrderCode_ask, _getFeeByOrderCode_sysTime, _getFeeByOrderCode_msg, _getFeeByOrderCode_baseFee, _getFeeByOrderCode_regFee, _getFeeByOrderCode_dealFee, _getFeeByOrderCode_insurance, _getFeeByOrderCode_totalFee, _getFeeByOrderCode_currencyCode, _getFeeByOrderCode_chargebackTime, _getFeeByOrderCode_chargebackWorkDay, _getFeeByOrderCode_shipTypeCode, _getFeeByOrderCode_subShipType, _getFeeByOrderCode_waybillCode, _getFeeByOrderCode_discount, _getFeeByOrderCode_otherFee, _getFeeByOrderCode_originBaseFee, _getFeeByOrderCode_originAddons, _getFeeByOrderCode_stDealFee, _getFeeByOrderCode_stRegFee, _getFeeByOrderCode_feeWeight);

        System.out.println("getFeeByOrderCode._getFeeByOrderCode_orderCode=" + _getFeeByOrderCode_orderCode.value);
        System.out.println("getFeeByOrderCode._getFeeByOrderCode_ask=" + _getFeeByOrderCode_ask.value);
        System.out.println("getFeeByOrderCode._getFeeByOrderCode_sysTime=" + _getFeeByOrderCode_sysTime.value);
        System.out.println("getFeeByOrderCode._getFeeByOrderCode_msg=" + _getFeeByOrderCode_msg.value);
        System.out.println("getFeeByOrderCode._getFeeByOrderCode_baseFee=" + _getFeeByOrderCode_baseFee.value);
        System.out.println("getFeeByOrderCode._getFeeByOrderCode_regFee=" + _getFeeByOrderCode_regFee.value);
        System.out.println("getFeeByOrderCode._getFeeByOrderCode_dealFee=" + _getFeeByOrderCode_dealFee.value);
        System.out.println("getFeeByOrderCode._getFeeByOrderCode_insurance=" + _getFeeByOrderCode_insurance.value);
        System.out.println("getFeeByOrderCode._getFeeByOrderCode_totalFee=" + _getFeeByOrderCode_totalFee.value);
        System.out.println("getFeeByOrderCode._getFeeByOrderCode_currencyCode=" + _getFeeByOrderCode_currencyCode.value);
        System.out.println("getFeeByOrderCode._getFeeByOrderCode_chargebackTime=" + _getFeeByOrderCode_chargebackTime.value);
        System.out.println("getFeeByOrderCode._getFeeByOrderCode_chargebackWorkDay=" + _getFeeByOrderCode_chargebackWorkDay.value);
        System.out.println("getFeeByOrderCode._getFeeByOrderCode_shipTypeCode=" + _getFeeByOrderCode_shipTypeCode.value);
        System.out.println("getFeeByOrderCode._getFeeByOrderCode_subShipType=" + _getFeeByOrderCode_subShipType.value);
        System.out.println("getFeeByOrderCode._getFeeByOrderCode_waybillCode=" + _getFeeByOrderCode_waybillCode.value);
        System.out.println("getFeeByOrderCode._getFeeByOrderCode_discount=" + _getFeeByOrderCode_discount.value);
        System.out.println("getFeeByOrderCode._getFeeByOrderCode_otherFee=" + _getFeeByOrderCode_otherFee.value);
        System.out.println("getFeeByOrderCode._getFeeByOrderCode_originBaseFee=" + _getFeeByOrderCode_originBaseFee.value);
        System.out.println("getFeeByOrderCode._getFeeByOrderCode_originAddons=" + _getFeeByOrderCode_originAddons.value);
        System.out.println("getFeeByOrderCode._getFeeByOrderCode_stDealFee=" + _getFeeByOrderCode_stDealFee.value);
        System.out.println("getFeeByOrderCode._getFeeByOrderCode_stRegFee=" + _getFeeByOrderCode_stRegFee.value);
        System.out.println("getFeeByOrderCode._getFeeByOrderCode_feeWeight=" + _getFeeByOrderCode_feeWeight.value);

        }
        {
        System.out.println("Invoking getShipTypes...");
        GetShipTypesRequest _getShipTypes_parameters = null;
        Shiptypes _getShipTypes__return = port.getShipTypes(_getShipTypes_parameters);
        System.out.println("getShipTypes.result=" + _getShipTypes__return);


        }
        {
        System.out.println("Invoking updateOrderStatus...");
        HeaderRequest _updateOrderStatus_headerRequest = null;
        UpdateOrderStatusInfoArray _updateOrderStatus_updateOrderInfo = null;
        String _updateOrderStatus_orderCode = "";
        javax.xml.ws.Holder<String> _updateOrderStatus_ask = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _updateOrderStatus_message = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> _updateOrderStatus_time = new javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar>();
        port.updateOrderStatus(_updateOrderStatus_headerRequest, _updateOrderStatus_updateOrderInfo, _updateOrderStatus_orderCode, _updateOrderStatus_ask, _updateOrderStatus_message, _updateOrderStatus_time);

        System.out.println("updateOrderStatus._updateOrderStatus_ask=" + _updateOrderStatus_ask.value);
        System.out.println("updateOrderStatus._updateOrderStatus_message=" + _updateOrderStatus_message.value);
        System.out.println("updateOrderStatus._updateOrderStatus_time=" + _updateOrderStatus_time.value);

        }
        {
        System.out.println("Invoking getRatesByType...");
        HeaderRequest _getRatesByType_headerRequest = null;
        GetRatesByTypeRequestInfo _getRatesByType_ratesRequestInfo = null;
        java.util.List<Rate> _getRatesByType__return = port.getRatesByType(_getRatesByType_headerRequest, _getRatesByType_ratesRequestInfo);
        System.out.println("getRatesByType.result=" + _getRatesByType__return);


        }
        {
        System.out.println("Invoking getRateByMode...");
        GetRateByMode _getRateByMode_parameters = null;
        Rate _getRateByMode__return = port.getRateByMode(_getRateByMode_parameters);
        System.out.println("getRateByMode.result=" + _getRateByMode__return);


        }
        {
        System.out.println("Invoking getRates...");
        HeaderRequest _getRates_headerRequest = null;
        GetRatesRequestInfo _getRates_ratesRequestInfo = null;
        java.util.List<Rate> _getRates__return = port.getRates(_getRates_headerRequest, _getRates_ratesRequestInfo);
        System.out.println("getRates.result=" + _getRates__return);


        }
        {
        System.out.println("Invoking addOrder...");
        AddOrderRequest _addOrder_parameters = null;
        AddOrderResponse _addOrder__return = port.addOrder(_addOrder_parameters);
        System.out.println("addOrder.result=" + _addOrder__return);


        }
        {
        System.out.println("Invoking updateOrderVolumeWeight...");
        UpdateOrderVolumeWeightRequest _updateOrderVolumeWeight_parameters = null;
        UpdateOrderVolumeWeightResponse _updateOrderVolumeWeight__return = port.updateOrderVolumeWeight(_updateOrderVolumeWeight_parameters);
        System.out.println("updateOrderVolumeWeight.result=" + _updateOrderVolumeWeight__return);


        }
        {
        System.out.println("Invoking searchOrder...");
        SearchOrderRequest _searchOrder_parameters = null;
        SearchOrderResponse _searchOrder__return = port.searchOrder(_searchOrder_parameters);
        System.out.println("searchOrder.result=" + _searchOrder__return);


        }
        {
        System.out.println("Invoking getClassTypes...");
        GetClassTypesRequest _getClassTypes_parameters = null;
        Classtypes _getClassTypes__return = port.getClassTypes(_getClassTypes_parameters);
        System.out.println("getClassTypes.result=" + _getClassTypes__return);


        }
        {
        System.out.println("Invoking updateOrder...");
        HeaderRequest _updateOrder_headerRequest = null;
        AddOrderRequestInfoArray _updateOrder_updateOrderInfo = null;
        String _updateOrder_orderCode = "";
        javax.xml.ws.Holder<String> _updateOrder_ask = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _updateOrder_message = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> _updateOrder_time = new javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar>();
        javax.xml.ws.Holder<String> _updateOrder_alert = new javax.xml.ws.Holder<String>();
        port.updateOrder(_updateOrder_headerRequest, _updateOrder_updateOrderInfo, _updateOrder_orderCode, _updateOrder_ask, _updateOrder_message, _updateOrder_time, _updateOrder_alert);

        System.out.println("updateOrder._updateOrder_ask=" + _updateOrder_ask.value);
        System.out.println("updateOrder._updateOrder_message=" + _updateOrder_message.value);
        System.out.println("updateOrder._updateOrder_time=" + _updateOrder_time.value);
        System.out.println("updateOrder._updateOrder_alert=" + _updateOrder_alert.value);

        }
        {
        System.out.println("Invoking batchAddOrders...");
        HeaderRequest _batchAddOrders_headerRequest = null;
        java.util.List<AddOrderRequestInfoArray> _batchAddOrders_orders = null;
        javax.xml.ws.Holder<String> _batchAddOrders_ask = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _batchAddOrders_operatingTime = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _batchAddOrders_message = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<java.util.List<AddOrderResponseData>> _batchAddOrders_data = new javax.xml.ws.Holder<java.util.List<AddOrderResponseData>>();
        port.batchAddOrders(_batchAddOrders_headerRequest, _batchAddOrders_orders, _batchAddOrders_ask, _batchAddOrders_operatingTime, _batchAddOrders_message, _batchAddOrders_data);

        System.out.println("batchAddOrders._batchAddOrders_ask=" + _batchAddOrders_ask.value);
        System.out.println("batchAddOrders._batchAddOrders_operatingTime=" + _batchAddOrders_operatingTime.value);
        System.out.println("batchAddOrders._batchAddOrders_message=" + _batchAddOrders_message.value);
        System.out.println("batchAddOrders._batchAddOrders_data=" + _batchAddOrders_data.value);

        }
        {
        System.out.println("Invoking reSetLabel...");
        HeaderRequest _reSetLabel_headerRequest = null;
        ReSetLabelInfoArray _reSetLabel_reSetLabelInfo = null;
        String _reSetLabel_orderCode = "";
        javax.xml.ws.Holder<String> _reSetLabel_ask = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _reSetLabel_message = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _reSetLabel_trackingNumber = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> _reSetLabel_time = new javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar>();
        port.reSetLabel(_reSetLabel_headerRequest, _reSetLabel_reSetLabelInfo, _reSetLabel_orderCode, _reSetLabel_ask, _reSetLabel_message, _reSetLabel_trackingNumber, _reSetLabel_time);

        System.out.println("reSetLabel._reSetLabel_ask=" + _reSetLabel_ask.value);
        System.out.println("reSetLabel._reSetLabel_message=" + _reSetLabel_message.value);
        System.out.println("reSetLabel._reSetLabel_trackingNumber=" + _reSetLabel_trackingNumber.value);
        System.out.println("reSetLabel._reSetLabel_time=" + _reSetLabel_time.value);

        }

        System.exit(0);
    }

}
