
package com.crossborder.entity;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import com.crossborder.service.Warehouse;

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-06-08T18:02:43.109+08:00
 * Generated source version: 2.7.14
 * 
 */
public final class Warehouse_WarehouseSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/ShipRate/", "Warehouse");

    private Warehouse_WarehouseSOAP_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = Warehouse_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Warehouse_Service ss = new Warehouse_Service(wsdlURL, SERVICE_NAME);
        Warehouse port = ss.getWarehouseSOAP();
        
        {
        System.out.println("Invoking getInventory...");
        GetInventoryRequest _getInventory_parameters = null;
       GetInventoryResponse _getInventory__return = port.getInventory(_getInventory_parameters);
        System.out.println("getInventory.result=" + _getInventory__return);


        }
        {
        System.out.println("Invoking getWarehouseShipType...");
        GetWarehouseShipTypeRequest _getWarehouseShipType_parameters = null;
        GetWarehouseShipTypeResponse _getWarehouseShipType__return = port.getWarehouseShipType(_getWarehouseShipType_parameters);
        System.out.println("getWarehouseShipType.result=" + _getWarehouseShipType__return);


        }
        {
        System.out.println("Invoking getWarehouse...");
        GetWarehouseRequestType _getWarehouse_parameters = null;
        Warehouses _getWarehouse__return = port.getWarehouse(_getWarehouse_parameters);
        System.out.println("getWarehouse.result=" + _getWarehouse__return);


        }
        {
        System.out.println("Invoking addWarehouseOrder...");
        AddWarehouseOrderRequest _addWarehouseOrder_parameters = null;
        AddWarehouseOrderResponse _addWarehouseOrder__return = port.addWarehouseOrder(_addWarehouseOrder_parameters);
        System.out.println("addWarehouseOrder.result=" + _addWarehouseOrder__return);


        }

        System.exit(0);
    }

}
