package com.crossborder.utils.amz.upload;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ProductTypeExt {

    public static Map<String,List<String>> list=new HashMap<>();
    static {
        List<String> materialType=new ArrayList<>();
        materialType.add("100-percent-cotton");
        materialType.add("Rubber");
        materialType.add("acetate");
        materialType.add("acrylic");
        materialType.add("alpaca");
        materialType.add("angora");
        materialType.add("blend");
        materialType.add("buckskin");
        materialType.add("calfskin");
        materialType.add("canvas");
        materialType.add("cashmere");
        materialType.add("cashmere-blend");
        materialType.add("chamois");
        materialType.add("cotton");
        materialType.add("cotton-blend");
        materialType.add("cotton-rich");
        materialType.add("crocodile");
        materialType.add("dacron");
        materialType.add("down");
        materialType.add("egyptian-cotton");
        materialType.add("elastic");
        materialType.add("exotic");
        materialType.add("fabric");
        materialType.add("faux-fur");
        materialType.add("fleece");
        materialType.add("fur");
        materialType.add("gore-tex");
        materialType.add("haircalf");
        materialType.add("hemp");
        materialType.add("kevlar");
        materialType.add("lace");
        materialType.add("leather");
        materialType.add("leather-and-fabric");
        materialType.add("leather-and-mesh");
        materialType.add("leather-and-rubber");
        materialType.add("leather-and-synthetic");
        materialType.add("linen");
        materialType.add("linen-blend");
        materialType.add("lizard");
        materialType.add("lurex");
        materialType.add("lycra");
        materialType.add("lycra-blend");
        materialType.add("mercerized-cotton");
        materialType.add("merino-wool");
        materialType.add("mesh");
        materialType.add("microfiber");
        materialType.add("microsuede");
        materialType.add("mohair");
        materialType.add("nappa-leather");
        materialType.add("neoprene");
        materialType.add("nubuck");
        materialType.add("nylon");
        materialType.add("ostrich");
        materialType.add("patent-leather");
        materialType.add("pima-cotton");
        materialType.add("plastic");
        materialType.add("pleather");
        materialType.add("polartec-fleece");
        materialType.add("poly-cotton");
        materialType.add("poly-rayon");
        materialType.add("polyester");
        materialType.add("polyester-blend");
        materialType.add("polypropylene");
        materialType.add("pony");
        materialType.add("rayon");
        materialType.add("rayon-blend");
        materialType.add("satin");
        materialType.add("shearling");
        materialType.add("sheepskin");
        materialType.add("shetland");
        materialType.add("silk");
        materialType.add("silk-blend");
        materialType.add("snakeskin");
        materialType.add("spandex");
        materialType.add("straw");
        materialType.add("suede");
        materialType.add("synthetic");
        materialType.add("synthetic-and-fabric");
        materialType.add("synthetic-and-leather");
        materialType.add("synthetic-and-mesh");
        materialType.add("synthetic-and-rubber");
        materialType.add("tencel");
        materialType.add("thinsulate");
        materialType.add("ultrasuede");
        materialType.add("urethane");
        materialType.add("velcro");
        materialType.add("velvet");
        materialType.add("vinyl");
        materialType.add("viscose");
        materialType.add("viscose-rayon");
        materialType.add("water-snake");
        materialType.add("wood");
        materialType.add("wool");
        materialType.add("wool-blend");
        materialType.add("worsted-wool");

        list.put("MaterialType", materialType);

        List<String> outerMaterialType = new ArrayList<>();
        outerMaterialType.add("Beaded");
        outerMaterialType.add("Canvas");
        outerMaterialType.add("Felt");
        outerMaterialType.add("Nubuck Leather");
        outerMaterialType.add("Patent Leather");
        outerMaterialType.add("Other Leather");
        outerMaterialType.add("Rubber");
        outerMaterialType.add("Satin");
        outerMaterialType.add("Silk");
        outerMaterialType.add("Smooth Leather");
        outerMaterialType.add("Suede Leather");
        outerMaterialType.add("Synthetic");
        outerMaterialType.add("Velvet");
        outerMaterialType.add("Wool");

        list.put("OuterMaterialType", outerMaterialType);

        List<String> styleName = new ArrayList<>();
        styleName.add("Ankle-Strap");
        styleName.add("Ballet");
        styleName.add("Ballroom");
        styleName.add("Biker Boots");
        styleName.add("Brogue");
        styleName.add("Chelsea Boots");
        styleName.add("Chukka Boots");
        styleName.add("Closed-Toe");
        styleName.add("Combat Boots");
        styleName.add("Cowboy Boots");
        styleName.add("Derby");
        styleName.add("Desert Boots");
        styleName.add("Espadrille");
        styleName.add("Flatform");
        styleName.add("Gladiator");
        styleName.add("High-Top");
        styleName.add("Jazz & Modern");
        styleName.add("Low-Top");
        styleName.add("Moccasin Boots");
        styleName.add("Open-back");
        styleName.add("Oxford");
        styleName.add("Peep-Toe");
        styleName.add("Platform");
        styleName.add("Slingback");
        styleName.add("Slouch Boots");
        styleName.add("Snow Boots");
        styleName.add("T-Bar");
        styleName.add("Tap");
        styleName.add("Wellington Boots");

        list.put("StyleName", styleName);

        List<String> cTye = new ArrayList<>();
        cTye.add("Buckle");
        cTye.add("Button");
        cTye.add("Lace-Up");
        cTye.add("Slip-On");
        cTye.add("Speed-Laces");
        cTye.add("Velcro");
        cTye.add("Zip");


        list.put("ClosureType", cTye);
    }

}
