package com.crossborder.service;

import com.crossborder.entity.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-06-08T18:02:43.265+08:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://www.example.org/ShipRate/", name = "Warehouse")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Warehouse {

    /**
     * 查询产品信息
     */
    @WebResult(name = "getInventoryResponse", targetNamespace = "http://www.example.org/ShipRate/", partName = "parameters")
    @WebMethod(action = "http://www.example.org/ShipRate/getInventory")
    public GetInventoryResponse getInventory(
            @WebParam(partName = "parameters", name = "getInventoryRequest", targetNamespace = "http://www.example.org/ShipRate/")
            GetInventoryRequest parameters
    );

    /**
     * 查询仓储运输方式
     */
    @WebResult(name = "getWarehouseShipTypeResponse", targetNamespace = "http://www.example.org/ShipRate/", partName = "parameters")
    @WebMethod(action = "http://www.example.org/ShipRate/getWarehouseShipType")
    public GetWarehouseShipTypeResponse getWarehouseShipType(
            @WebParam(partName = "parameters", name = "getWarehouseShipTypeRequest", targetNamespace = "http://www.example.org/ShipRate/")
            GetWarehouseShipTypeRequest parameters
    );

    /**
     * 查询仓储服务
     */
    @WebResult(name = "getWarehouseResponce", targetNamespace = "http://www.example.org/ShipRate/", partName = "parameters")
    @WebMethod(action = "http://www.example.org/ShipRate/getWarehouse")
    public Warehouses getWarehouse(
            @WebParam(partName = "parameters", name = "getWarehouseRequest", targetNamespace = "http://www.example.org/ShipRate/")
            GetWarehouseRequestType parameters
    );

    /**
     * 添加仓储订单
     */
    @WebResult(name = "addWarehouseOrderResponse", targetNamespace = "http://www.example.org/ShipRate/", partName = "parameters")
    @WebMethod(action = "http://www.example.org/ShipRate/addWarehouseOrder")
    public AddWarehouseOrderResponse addWarehouseOrder(
            @WebParam(partName = "parameters", name = "addWarehouseOrderRequest", targetNamespace = "http://www.example.org/ShipRate/")
            AddWarehouseOrderRequest parameters
    );
}
